name: 05 - 1 - Events Filters and Activity Types

on:
    pull_request:
        types:
            - opened
            - synchronized
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenever a PR is opened or synchronized AND branch is main"